package me.asleepp.skriptnexo.elements.events;

import ch.njol.skript.doc.Description;
import ch.njol.skript.doc.Examples;
import ch.njol.skript.doc.Name;
import ch.njol.skript.doc.Since;
import ch.njol.skript.lang.Literal;
import ch.njol.skript.lang.SkriptEvent;
import ch.njol.skript.lang.SkriptParser;
import org.skriptlang.skript.bukkit.lang.eventvalue.EventValue;
import org.skriptlang.skript.bukkit.lang.eventvalue.EventValueRegistry;
import org.skriptlang.skript.bukkit.registration.BukkitSyntaxInfos;
import org.skriptlang.skript.registration.SyntaxRegistry;
import com.nexomc.nexo.api.events.resourcepack.NexoPostPackGenerateEvent;
import me.asleepp.skriptnexo.SkriptNexo;
import org.bukkit.event.Event;
import team.unnamed.creative.ResourcePack;

import javax.annotation.Nullable;

@Name("On Post Pack Generate")
@Description({"Fires after all files are generated by Nexo, but before the pack is obfuscated."})
@Examples({"on post pack generate:"})
@Since("1.0")
public class EvtPostPackGenerateEvent extends SkriptEvent {

    @SuppressWarnings("unchecked")
    private static void register() {
        SyntaxRegistry syntaxRegistry = SkriptNexo.getAddonInstance().syntaxRegistry();
        syntaxRegistry.register(BukkitSyntaxInfos.Event.KEY,
            BukkitSyntaxInfos.Event.builder(EvtPostPackGenerateEvent.class, "Post Pack Generate")
                .addEvent(NexoPostPackGenerateEvent.class)
                .addPatterns("post pack generate")
                .supplier(EvtPostPackGenerateEvent::new)
                .build());
        EventValueRegistry evr = SkriptNexo.getAddonInstance().registry(EventValueRegistry.class);
        evr.register(EventValue.simple(NexoPostPackGenerateEvent.class, ResourcePack.class, NexoPostPackGenerateEvent::getResourcePack));
    }

    static { register(); }

    @Override
    public boolean init(Literal<?>[] args, int matchedPattern, SkriptParser.ParseResult parseResult) {
        return true;
    }

    @Override
    public boolean check(Event e) {
        return e instanceof NexoPostPackGenerateEvent;
    }

    @Override
    public String toString(@Nullable Event e, boolean debug) {
        return "post pack generate";
    }
}